import type { Metadata } from "next";
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import { Geist, Geist_Mono, Montserrat, Open_Sans} from "next/font/google";
import "./globals.css";
import './styles/base.css';
import './styles/components.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ['latin'],
})

const open_sans = Open_Sans({
  variable: "--font-open_sans",
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${open_sans.variable} antialiased`}
      >
        <div className="min-h-screen bg-gray-900 font-montserrat">  {/**bg-gradient-to-r from-blue-900  to-green-900 */}
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
